# Generated by Django 6.1 on 2026-09-19 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_priority_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='priority',
            old_name='name',
            new_name='prior_name',
        ),
    ]
